version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: url-shortener-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=url_shorten  # Added this line to set database name

volumes:
  mongodb_data: